name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./js
        recurse: true
        output_dir: ./out
